# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    image: employee:latest
    environment:
      - USER_NAME=root
      - DB_NAME=employee
      - PASSWORD=example
      - HOST_NAME=database-emp
    ports:
      - 8000:8000
    networks:
      - local

networks:
  local:
    driver: bridge