# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    image: ${CONTAINER_REGISTRY_UNAME}/essp:latest
    environment:
      - USER_NAME=${DB_USER_NAME}
      - DB_NAME=${DB_NAME}
      - PASSWORD=${DB_PASSWORD}
      - HOST_NAME=${DB_HOST_NAME}
    ports:
      - 8000:8000
    networks:
      - local

networks:
  local:
    driver: bridge