# Generated by Django 4.1.4 on 2023-11-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
