# Generated by Django 4.1.4 on 2022-12-31 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_first_name', models.CharField(max_length=30)),
                ('legal_last_name', models.CharField(max_length=30)),
                ('pref_first_name', models.CharField(max_length=30)),
                ('pref_last_name', models.CharField(max_length=30)),
                ('NIC', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('country_of_birth', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=10)),
                ('ethnicity', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('citizenship_status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
        ),
    ]
