# Generated by Django 4.1.4 on 2022-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_first_name', models.CharField(max_length=30)),
                ('legal_last_name', models.CharField(max_length=30)),
                ('pref_first_name', models.CharField(max_length=30)),
                ('pref_last_name', models.CharField(max_length=30)),
                ('NIC', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('country_of_birth', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=10)),
                ('ethnicity', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('citizenship_status', models.CharField(max_length=20)),
            ],
        ),
    ]
